### ISSUE TITLE
Commands in text or additional parameter

### ISSUE THREAD

**Issue by HeyDennis** [scottleedavis/mattermost-plugin-remind#179]
#### Summary

Support commands (beginning with "/") in text part.

#### Describe alternatives you've considered

Another parameter field for commands

#### Additional context

Example:
/remind me "/away" everyday at 16:00PM
![grafik](https://user-images.githubusercontent.com/47058862/76317101-e0607880-62db-11ea-8a9c-873fbf84f7f3.png)

**Comment by scottleedavis** [comment]
although I like the idea @HeyDennis , I feel this could lead to abuse in some cases.  Open to thoughts otherwise.  slack doesn't have the behaviour.

<img width="472" alt="Screen Shot 2020-05-10 at 4 43 43 PM" src="https://user-images.githubusercontent.com/2914443/81513450-7e24f380-92dd-11ea-8955-d2bbfc0cbeb0.png">
