### ISSUE TITLE
Reminders that can occur within the current day should state and remind the user that day. "tomorrow" > "today"

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/mattermost-plugin-remind#33]
for example, 

scheduling at 4:51pm for something at 5pm, should schedule it at the same day, not tomorrow.

**Comment by scottleedavis** [comment]
fixed by switching to common utc as storage some commits ago.

**Comment by hadret** [comment]
This is bug is back. Example taken from the wiki:

```
/remind me Pickup kids at 4:30pm
```

This will default to 4:30pm tomorrow even if it's before 4:30pm today.

**Comment by scottleedavis** [comment]
Hi @hadret , could you describe the scenario you are seeing this as?  Is experimental timezone enabled?  I am not able to reproduce this _not_ working.

![test](https://user-images.githubusercontent.com/2914443/61809002-536eba80-adf1-11e9-9e9b-f5bab7e2c013.gif)

**Comment by hadret** [comment]
I enabled the experimental TZ feature (and set correct timezone in user settings) and still when I type: `/remind me bla bla at 8pm` it defaults to tomorrow, even though it's ~7pm now.

**Comment by hadret** [comment]
Could you try staying in either am or pm when setting up the reminder? As in it’s pm in your timezone already and you setup reminder for later hour also in pm?

**Comment by scottleedavis** [comment]
@hadret Are you using version 0.4.1?  What mattermost version?

Just tested pm->pm with no issues.
![pm](https://user-images.githubusercontent.com/2914443/61825088-7494d280-ae14-11e9-88e4-ce37e37ab7a2.gif)

**Comment by scottleedavis** [comment]
![second_pm](https://user-images.githubusercontent.com/2914443/61825720-c9851880-ae15-11e9-95e4-cce1dd7697ee.gif)

could you share a animated gif or screenshot?   I am not able to reproduce.

**Comment by hadret** [comment]
I'm no longer able to reproduce it today 🤷‍♂

Just to make things complete: I'm using latest version of the plugin and Mattermost 5.12 (latest version shipped with GitLab).

It may have been the TZ settings that after all got it fixed, but I'm not entirely sure (especially due to the fact that it was only `at` syntax that was defaulting to tomorrow -- if I used `in` it was working and counting just fine).

I'll get back to you should it happen again. Thanks for your support and great plugin! 👍
