### ISSUE TITLE
Handle < 1 day recurring reminders 

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/mattermost-plugin-remind#67]
@cpanato reported in channel on community.mattermost.com:

i tried to issue this command: `/remind me to take a break every 45 minutes` but got an error

Slack does not support recurring reminders under the day time span.  Perhaps this plugin should?  Open to thoughts.

**Comment by cpanato** [comment]
i was thinking more about this and we need to limit as well like
`/remind me to take a break every 45 minutes between 8-17` or `/remind me to take a break every 45 minutes during weekdays` or something like that

otherwise you can get messages when you dont want :) but also there is a case that you want :)

**Comment by scottleedavis** [comment]
I like the idea though not immediately sure how to set the boundaries. 

 '/remind me hey every second' is a tax on the system if distributed and also likely wasteful.  Maybe not though?

'/remind me take a break every 45 minutes  weekdays between 9am and 5pm' could work... But not sure the final patterns supported.

@esethna do you have thoughts?  Slack didn't do this for some reason and I am not sure why.  Should remindbot?

**Comment by scottleedavis** [comment]
Opening this up to help wanted.  Would be a great feature added.

**Comment by scottleedavis** [comment]
https://github.com/scottleedavis/mattermost-plugin-remind/issues/177
